### ISSUE TITLE
calico v1.1.0 network policy doesn't work on kubernetes v1.6.4  

### ISSUE THREAD

**Issue by jeffchanjunwei** [projectcalico/kube-controllers#120]
I deploy calico with ipip mode on kubernetes, but the network policy of extensions/v1beta1 not work. I check the iptables rules on nodes but can not find the specific rule of policy. However, policy and profile in calico, network policy and namespace in kubernetes, are both created, pods without specific label or in other namespace still can visit. How can I  fix it？

**_Version_**
calico: v2.1 （calico/node v1.1.0）
cni_plugin(calico calico-ipam): v1.10
calico/kube-policy-controller:v0.5.2
kubernetes: v1.6.4
networkpolicy api version: extensions/v1beta1

**_tested network policy_** 

```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: xxx
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: centos-xxx
    ports:
    - port: 80
      protocol: TCP
  podSelector:
    matchLabels:
      app: nginx-xxx
```

the above pod cento and nginx in namespace xxx have labels "app: centos-xxx",  "app: nginx-xxx" seprately.

**_namespace config_**
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    net.beta.kubernetes.io/network-policy: '{"ingress": {"isolation": "DefaultDeny"}}'
  creationTimestamp: 2017-08-23T08:44:43Z
  name: xxx
  resourceVersion: "23963694"
  selfLink: /api/v1/namespacesxxx
  uid: 4ef654d6-87df-11e7-a7d4-005056bc50a0
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

**Comment by tmjd** [comment]
If this is a new cluster I'd suggest using a newer Calico version than v2.1 (unless there is a specific reason you need v2.1), there have been many fixes and improvements.

You may want to check the logs for errors on your calico/kube-policy-controller.  It is responsible for taking NetworkPolicy and translating it into etcd.  You could also check calico-node logs but for an issue like this I'd start with the kube-policy-controller.

One thing to be aware of is that the iptables rules for a policy will only be added to a node if there are pods that the policy apply to on that node.  You might already be aware but I wanted to make sure you knew.

**Comment by jeffchanjunwei** [comment]
@tmjd ,thx erik. I have update the calico version to v2.4.1 and  calico-policy-controller to v0.6.0. I also check  the etcd and find the relevant policy element in it. 

The logs of kube-policy-controller about the relevant pod are showed below 

```
2017-08-29 03:28:32,408 6 INFO Handled MODIFIED for Pod: (u'chenjunwei', u'centos-chenjunwei-3234200556-4tm0w')
2017-08-29 03:28:32,409 6 INFO Handled MODIFIED for Pod: (u'chenjunwei', u'centos-chenjunwei-3234200556-gnzts')
2017-08-29 03:28:32,409 6 INFO Handled MODIFIED for Pod: (u'chenjunwei', u'centos-forbi-3162044878-2lwkg')
2017-08-29 03:28:32,410 6 INFO Handled MODIFIED for Pod: (u'chenjunwei', u'centos-forbi-3162044878-33qv7')
2017-08-29 03:28:32,462 6 INFO Handled MODIFIED for Pod: (u'default', u'centos-forbi-3162044878-s0ppc')
2017-08-29 03:28:32,463 6 INFO Handled MODIFIED for Pod: (u'default', u'centos-forbi-3162044878-tvs3b')
2017-08-29 03:28:32,411 6 INFO Handled MODIFIED for Pod: (u'chenjunwei', u'nginx-chenjunwei-2486570784-r4063')
2017-08-29 03:28:32,411 6 INFO Handled MODIFIED for Pod: (u'chenjunwei', u'nginx-chenjunwei-2486570784-scb38')
```

And the docker logs calico/node also can not supply any useful info 
```
Skipping datastore connection test
Using IPv4 address from environment: IP=10.132.46.144
IPv4 address 10.132.46.144 discovered on interface ens192
No AS number configured on node resource, using global value
Using node name: paasn2
time="2017-08-29T01:56:05Z" level=info msg="Loading config from environment" 
time="2017-08-29T01:56:05Z" level=info msg="IPIP tunnel address is still valid" IP=182.169.55.64 
Starting libnetwork service
Calico node started successfully
```

Do u have any other idea to this issue

**Comment by tmjd** [comment]
If the way you updated calico was to apply a new manifest or update the versions in the manifest and re-applied you also need to restart (delete) the calico-node pods to complete the update.  (I wanted to mention that because people regularly don't realize that restarting the nodes is needed.)
Also if you're updating to Calico v2.4.1 then the calico-policy-controller should be at v0.7.0 and CNI should be v1.10.0.  I don't think it would be a problem with what you have though.

So you know, the DefaultDeny behavior changed with 2.4.1 so no longer does setting the annotation on the namespace produce deny.  Now any pod that is selected by a NetworkPolicy will have traffic denied (ingress) that is not explicitly allowed.

Can you use calicoctl to query the network policies `calicoctl get policies -o yaml`, you should see the policies that were created as K8s NetworkPolicies and translated by calico-policy-controller and inserted into etcd.  If you need help getting it installed or configured see https://docs.projectcalico.org/v2.4/usage/calicoctl/install-and-configuration.
You can also do `calicoctl get wep -o yaml` to see the workload endpoints that Calico is aware of.  This equates to the pods that have been networked, you should be able to cross reference the calico policies and the weps (using the selectors).  I'm suggesting this because it sounds like you are seeing policy take effect (the deny) but your `centos-xxx` pod does not seem to have the correct labels.

**Comment by jeffchanjunwei** [comment]
@tmjd thx. After updating kube-policy-controller to v0.7.0, it's solved. I also delete the namespace annotations. 
Can I make sure that, for kubernetess version 1.6.4, network policy api extensions/v1beta1, bellow default "isolation" or "allow traffic" policies work? In my cluster,  It seems doesn't work. If it is true, how can I define a default policy of all pods


```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector:
```
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
spec:
  podSelector:
  ingress:
  - {}
```

**Comment by tmjd** [comment]
Since you are using Kubernetes 1.6.x I think you probably need to change your
`apiVersion: networking.k8s.io/v1`
to
`apiVersion: extensions/v1beta1`

I don't think the NetworkPolicy API came out of beta until 1.7, which is why I think that is needed.

**Comment by tmjd** [comment]
@jeffchanjunwei Did my suggestion above help resolve your problem?  I'm wondering if this issue can be closed if things are working for you now.

**Comment by jeffchanjunwei** [comment]
@tmjd , sorry for my late response. It doesn't work after changing into "apiVersion: extensions/v1beta1" in my environment. The iptables doesn't have any change when deploy "default-deny" or "allow-all" policy. Do u have any idea about the iptables doesn't update according to the policy? Do I need to do something to the os network module?

**Comment by tmjd** [comment]
Did you deploy pods to your cluster and check iptables on nodes with pods deployed? iptables rules will not be written unless there are pods that they apply to on a host.

I'm not sure what you are referring to about os network module. If you are running NetworkManager or something like that then I believe there is the potential for problems and so you shouldn't be using it.

Can you be more detail on what you mean by "doesn't work"? Does traffic pod-to-pod or host-to-local-pod work?

**Comment by caseydavenport** [comment]
@jeffchanjunwei one good thing to check is to see if the node has any Calico networked pods running on it.

You can do that by running this command on one of your nodes that has Pods running:

```
ip route show | grep cali
```

If no routes show up, then most likely:
- There are no pods running on that node, OR
- The pods that are running have not been networked via Calico.

If either of those is true, then you won't see the iptables change on that node.

**Comment by caseydavenport** [comment]
@jeffchanjunwei did you ever figure out the problem?

**Comment by caseydavenport** [comment]
Closing this for now due to inactivity.
