### ISSUE TITLE
policy controller should exit if RBAC enabled and no permission

### ISSUE THREAD

**Issue by mattymo** [projectcalico/kube-controllers#121]
The policy controller continuously errors, but never exits if RBAC is enabled in the k8s controller, but the correct cluster settings are not made.

## Expected Behavior

The policy controller should exit with a nonzero value if it cannot fetch information on pods/namespaces/etc.
## Current Behavior

The pod is running, but has similar messages in the logs:
```
2017-09-01 09:35:13,506 11 ERROR Unhandled exception killed Pod manager
Traceback (most recent call last):
  File "<string>", line 320, in _manage_resource
  File "<string>", line 437, in _sync_resources
  File "site-packages/requests/models.py", line 866, in json
  File "site-packages/simplejson/__init__.py", line 516, in loads
  File "site-packages/simplejson/decoder.py", line 370, in decode
  File "site-packages/simplejson/decoder.py", line 400, in raw_decode
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
## Possible Solution

Option 1: automatically fail
Option 2: add another env var to fail on k8s access issues

## Your Environment

* Kubernetes version (`kubectl version`): v1.7.3
* Manifest file used to deploy k8s policy: https://github.com/kubernetes-incubator/kubespray/blob/master/roles/kubernetes-apps/policy_controller/calico/templates/calico-policy-controller.yml.j2
* Operating System and version: Ubuntu Xenial
* Link to your project (optional): https://github.com/kubernetes-incubator/kubespray/

**Comment by caseydavenport** [comment]
I think this is a good candidate for something that would be caught by a Kubernetes liveness check as per #44

**Comment by rayburgemeestre** [comment]
Just a note for anyone stumbling upon this. In my case I had expired certificates, fixed them with kubeadm, but apparently there were still tokens that were generated with the old certificates. So I deleted those secrets and after that this service started working properly again. I had to delete the pod though and wait for it to be recreated
