### ISSUE TITLE
Failed to start/ Invalid configuration

### ISSUE THREAD

**Issue by valentin2105** [projectcalico/kube-controllers#194]
Hi,

I try to upgrade my Calico Policy-controller from v0.7.0 to v1.0.x and I got this error : 

```
[INFO][1] main.go 65: Loaded configuration from environment config=&config.Config{LogLevel:"info", ReconcilerPeriod:"5m", EnabledControllers:"policy,profile,endpoint", EndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, Kubeconfig:""}
[INFO][1] client.go 202: Loading config from environment
[FATAL][1] main.go 77: Failed to start error=failed to build kubernetes client config: invalid configuration: no configuration has been provided
```

My policy-controller run with theses args : 

```
        - name: ETCD_ENDPOINTS
          value: http://k8s.srv.domain.tld:2379
        - name: K8S_API
          value: https://k8s.srv.domain.tld:6443
        - name: KUBERNETES_PORT
          value: https://k8s.srv.domain.tld:6443
        - name: KUBERNETES_PORT_443_TCP
          value: https://k8s.srv.domain.tld:6443
        - name: CONFIGURE_ETC_HOSTS
          value: "false"
```

Thanks !

**Comment by tmjd** [comment]
Typically it is not necessary to specify any Kubernetes config to the policy(kube)-controller, outside of K8S_API, could you try removing KUBERNETES_PORT and KUBERNETES_PORT_443_TCP and see if that helps?  TBH I don't see that those environment variables are used anywhere so don't have much hope that they will fix it.

Do you perhaps have any 'special' flags on your kubelet or apiserver that might prevent the 'standard' setup of the kubernetes service accounts or configuration created for K8s api access for pods?  I'm not specifically aware of any that would prevent that but since some configuration appears to be not set I thought I'd check if you've got anything 'out of the ordinary'.

**Comment by valentin2105** [comment]
I have deleted the two env variables and got the same results : 
```
2017-12-08 04:28:57.808 [INFO][1] main.go 65: Loaded configuration from environment config=&config.Config{LogLevel:"info", ReconcilerPeriod:"5m", EnabledControllers:"policy,profile,endpoint", EndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, Kubeconfig:""}
2017-12-08 04:28:57.808 [INFO][1] client.go 202: Loading config from environment
2017-12-08 04:28:57.808 [FATAL][1] main.go 77: Failed to start error=failed to build kubernetes client config: invalid configuration: no configuration has been provided
```

I don't have any special flags but I use IPv6-Only Kubernetes cluster. 
With v0.7.x, I don't get any problem but I needed to specify `KUBERNETES_PORT` & `KUBERNETES_PORT_443_TCP`. 

Also, when the stable v1.0.1 will be available in the Dockerhub ? 

Thanks !!

**Comment by valentin2105** [comment]
It work with theses variables : 


```
        - name: ETCD_ENDPOINTS
          value: "http://k8s.domain.tld:2379"
        - name: K8S_API
          value: "https://k8s.domain.tld:6443"
        - name: KUBERNETES_PORT
          value: '6443'
        - name: KUBERNETES_SERVICE_PORT
          value: '6443'
        - name: KUBERNETES_SERVICE_HOST
          value: "k8s.domain.tld"
        - name: KUBERNETES_MASTER
          value: "https://k8s.domain.tld:6443"
        - name: KUBERNETES_PORT_443_TCP
          value: '6443'
        - name: CONFIGURE_ETC_HOSTS
          value: "false"
```

**Comment by wottui** [comment]
How to solve your problem

**Comment by wottui** [comment]
Can you tell me，thanks
