### ISSUE TITLE
kube-controllers can get stuck, unable to connect to etcd

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/kube-controllers#199]
From IRC user *anticw*:

> using calico v2.6.2 on k8s v1.8.4 it's not uncommon for me to see messages to the effect "pod_controller.go 198: Failed to load workload endpoint cache, retrying in 5s error=client: etcd cluster is unavailable or misconfigured; error #0: client: ... exceeded header timeout"
>
> killing the controller and it seems to 'come right'
> i'm guessing this is an arfiact of things restarting ... even so ... if it's not right why doesn't it terminate and respawn or update?

## Expected Behavior

The controller should either reconnect successfully, or die and be restarted.

## Current Behavior

Can get stuck as above.

## Possible Solution

Add health checks (#44) and include a check that the controller was successfully connected to etcd within the last x seconds.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Kubernetes version (`kubectl version`): v1.8.4
* Manifest file used to deploy k8s policy:
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
yeah, I think it's doing the right thing -  we don't want to restart every time we fail to connect to etcd.

What we should do is have a liveness probe that will kill the controllers if it can't connect to etcd for an extended period of time (say a minute or two).
