### ISSUE TITLE
Allow forcefully sync node state

### ISSUE THREAD

**Issue by r7vme** [projectcalico/kube-controllers#204]
## Expected Behavior

Node controller does not cover following use case:
1) Cluster in "dirty state" some dead Calico nodes are not cleaned up (But removed from Kubernetes).
2) New node controller started.
3) Dead nodes will not be cleaned up.

## Current Behavior
Dead (Unknown for node-controler) nodes will not be cleaned up. And no "force" option to overwrite this.

## Context
We have used separate [calico-node-controller](https://github.com/giantswarm/calico-node-controller) forked from @caseydavenport . So now when we upgrading Calico from 2.6.2 to 2.6.5 we are removing old one and applying official one. But because we are recreating master node we are hitting situation when "old" node controller already stopped and then node got removed from k8s and after "new" official one starts. So we are in situation when old master entry is still present in Calico state.

## Possible Solution
Allow "force" sync that will clean up all nodes from Calico that are not part of Kubernetes.

## Your Environment
* Kubernetes version (`kubectl version`): 1.8.4
* Manifest file used to deploy k8s policy: We are using slightly modified official [hosted manifests](https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/hosted).
* Operating System and version: CoreOS 1576.4.0
* Link to your project (optional): https://github.com/giantswarm/calico-node-controller

**Comment by caseydavenport** [comment]
@r7vme are you imagining more of a "one-shot" execution prior to running the node controller, or an option passed to the running controller itself telling it to be more strict?

**Comment by r7vme** [comment]
"on-shot" is interesting, but i'm thinking about more strict behavior.

For my interest, did i understand right?
1) stop node-controller
2) delete node from k8s
3) start node-controller
4) deleted node will stay in Calico? or will be deleted, because there are some other state already?

**Comment by caseydavenport** [comment]
The current behavior is that any node which exists in Calico but not in k8s will be left there.

So, in your scenario, step 4 would be "Deleted node stays in Calico".  This was implemented this way because there are a number of users doing mixed deployments where deleting non-k8s nodes is not the right behavior. 

A strict mode should be possible, I think. I'll mull on it a bit more to see if there are any complications.

CC @ozdanborne

**Comment by calvix** [comment]
Is there any movement on this matter? We would really appreciate this as this bug is currently affecting our workloads.

We can contribute to the solution if necessary.

**Comment by calvix** [comment]
Hello @caseydavenport ,
Thaks for the info. Configuration with `CALICO_K8S_NODE_REF` seems to work nicely and old nodes are being cleared even if the kubecontroller is offline during delete event.

**Comment by calvix** [comment]
We can close this: cc @r7vme

**Comment by caseydavenport** [comment]
@calvix thanks for the update, and glad that worked for you :)

I'm going to close this for now.
