### ISSUE TITLE
Failed to start error=failed to build kubernetes client config: invalid configuration: no configuration has been provided

### ISSUE THREAD

**Issue by jesse1993** [projectcalico/kube-controllers#274]
## Expected Behavior
pod calico-kube-controllers normal operation

## Current Behavior
all logs from container calico-kube-controllers:
2018-07-12 12:28:49.494 [INFO][1] main.go 69: Loaded configuration from environment  config=&config.Config{LogLevel:"info", ReconcilerPeriod:"5m", CompactionPeriod:"10m", EnabledControllers:"policy,profile,workloadendpoint,node", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:""}
2018-07-12 12:28:49.497 [FATAL][1] main.go 81: Failed to start error=failed to build kubernetes client config: invalid configuration: no configuration has been provided

## Steps to Reproduce (for bugs)
kubectl apply -f \
https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml

## Context
pod calico-kube-controllers startup failure

kubectl --server 172.18.11.249:8080 get po --all-namespaces
NAMESPACE     NAME                                       READY     STATUS             RESTARTS   AGE
default       etcd-server-master1                        1/1       Running            5          2d
default       etcd-server-master2                        1/1       Running            3          2d
default       kube-apiserver-master1                     1/1       Running            5          2d
default       kube-apiserver-master2                     1/1       Running            3          2d
default       kube-controller-manager-master1            1/1       Running            9          2d
default       kube-controller-manager-master2            1/1       Running            7          2d
default       kube-scheduler-master1                     1/1       Running            9          2d
default       kube-scheduler-master2                     1/1       Running            6          2d
kube-system   calico-etcd-bphrm                          1/1       Running            0          3h
kube-system   calico-etcd-c6h66                          1/1       Running            0          3h
kube-system   calico-kube-controllers-7bc7cd589b-ccbcw   0/1       CrashLoopBackOff   48         3h
kube-system   calico-node-44lsp                          1/2       CrashLoopBackOff   40         3h
kube-system   calico-node-p7x8m                          1/2       CrashLoopBackOff   57         3h
kube-system   calico-node-qlwss                          1/2       CrashLoopBackOff   54         3h
kube-system   calico-node-v5pzk                          1/2       CrashLoopBackOff   39         3h
kube-system   kube-proxy-master1                         1/1       Running            2          4h
kube-system   kube-proxy-master2                         1/1       Running            0          4h
kube-system   kube-proxy-worker1                         1/1       Running            1          2h
kube-system   kube-proxy-worker2                         1/1       Running            1          2h

## Your Environment

* Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
* Manifest file used to deploy k8s policy:
* Operating System and version:
centos7

**Comment by jesse1993** [comment]
The kube-controllers container can't start，so i don't know how to check that that information is available to the kube-controllers pod, can you give me some advice? and i checked the calico-node pod, it's environment variables is available, both of them are on the same node, thanks for the reply.

**Comment by caseydavenport** [comment]
I believe this is likely due to the same issue as this: https://github.com/projectcalico/cni-plugin/issues/560

My guess is that the cluster is not configured to provide serviceaccount tokens, and so the client isn't getting the expected token.

I believe you'll need some options on the controller manager to get it to sign JWT tokens for serviceaccounts.

**Comment by jesse1993** [comment]
sorry for my late response, i tried changing the config as per your suggestion, but i got the same error
[root@master1 ~]# kubectl --server 172.18.11.249:8080 get secrets -n kube-system
NAME                                  TYPE                                  DATA      AGE
calico-cni-plugin-token-54mt2         kubernetes.io/service-account-token   2         2m
calico-kube-controllers-token-qpzh8   kubernetes.io/service-account-token   2         2m
default-token-9jmhg                   kubernetes.io/service-account-token   2         21m

**error log:**
2018-07-16 11:31:39.240 [INFO][1] main.go 69: Loaded configuration from environment config=&config.Config{LogLevel:"info", ReconcilerPeriod:"5m", CompactionPeriod:"10m", EnabledControllers:"policy,profile,workloadendpoint,node", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:""}
2018-07-16 11:31:39.243 [FATAL][1] main.go 81: Failed to start error=failed to build kubernetes client config: invalid configuration: no configuration has been provided

**Comment by jesse1993** [comment]
@caseydavenport thanks a lot, the issue has been solved as per your suggestion, i have not recreate pod after modifying the configuration yesterday.
 [Managing Service Accounts](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/) says it adds a volumeSource to each container of the pod mounted at /var/run/secrets/kubernetes.io/serviceaccount when the pods are created or modified

**Comment by tmjd** [comment]
Since this is solved I'm closing this.  If it should be reopened please let me know.
