### ISSUE TITLE
unable to recognize "https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml": Get https://172.34.2.27:6443/api?timeout=32s: dial tcp 172.34.2.27:6443: connect: connection refused

### ISSUE THREAD

**Issue by lijodigiledge** [projectcalico/kube-controllers#290]
I tried kubernetes command
kubectl apply -f https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml

**Comment by caseydavenport** [comment]
@lijodigiledge could you please provide a bit more information? What is producing this error?

Please fill out the issue template for future issues.
