### ISSUE TITLE
panic on K8s node delete

### ISSUE THREAD

**Issue by ravilr** [projectcalico/kube-controllers#341]
calico kube-controller panics whenever 'kubectl delete node' is issued on Kube-api.

## Expected Behavior

no panic

## Current Behavior

```
panic: interface conversion: interface {} is nil, not *v3.Node
goroutine 107 [running]:
github.com/projectcalico/kube-controllers/pkg/controllers/node.(*NodeController).OnUpdates(0xc000362280, 0xc000379000, 0x1, 0x1)
	/go/src/github.com/projectcalico/kube-controllers/pkg/controllers/node/node_syncer.go:70 +0x6e0
github.com/projectcalico/kube-controllers/vendor/github.com/projectcalico/libcalico-go/lib/backend/watchersyncer.(*watcherSyncer).sendUpdates(0xc000388720, 0xc000379000, 0x1, 0x1, 0x1239a20, 0xc001239760, 0xc000379000)
	/go/src/github.com/projectcalico/kube-controllers/vendor/github.com/projectcalico/libcalico-go/lib/backend/watchersyncer/watchersyncer.go:236 +0xf3
github.com/projectcalico/kube-controllers/vendor/github.com/projectcalico/libcalico-go/lib/backend/watchersyncer.(*watcherSyncer).run(0xc000388720, 0x1634ba0, 0xc0002829c0)
	/go/src/github.com/projectcalico/kube-controllers/vendor/github.com/projectcalico/libcalico-go/lib/backend/watchersyncer/watchersyncer.go:168 +0x2bf
github.com/projectcalico/kube-controllers/vendor/github.com/projectcalico/libcalico-go/lib/backend/watchersyncer.(*watcherSyncer).Start.func1(0xc000388720, 0x1634ba0, 0xc0002829c0)
	/go/src/github.com/projectcalico/kube-controllers/vendor/github.com/projectcalico/libcalico-go/lib/backend/watchersyncer/watchersyncer.go:102 +0x3f
created by github.com/projectcalico/kube-controllers/vendor/github.com/projectcalico/libcalico-go/lib/backend/watchersyncer.(*watcherSyncer).Start
	/go/src/github.com/projectcalico/kube-controllers/vendor/github.com/projectcalico/libcalico-go/lib/backend/watchersyncer/watchersyncer.go:101 +0x12d
```
## Steps to Reproduce (for bugs)

1.  do  a 'kubectl delete node <node> on K8s.  kube-controller pod restarts after a panic.
2.
3.
4.

## Your Environment

* Kubernetes version (`kubectl version`):  v1.12.3
* Manifest file used to deploy k8s policy: Calico v3.5.1, calico/kube-controllers:v3.5.1
* Operating System and version: centos
* Link to your project (optional):

**Comment by ravilr** [comment]
@fasaxc @caseydavenport  what is the impact of panic here other than failing to clear the nodemap. does it affect networking in any way? I'm trying to understand whether this warrants a rollback of the upgrade we did(from 3.1.1 to 3.5.1) because of this issue.

**Comment by caseydavenport** [comment]
@ravilr I'd expect that the controller pod will restart and then successfully continue - you should see it handle the node deletion on startup. If that's the case, then this should be more or less benign and won't impact networking.

if you're seeing it get stuck in a crash loop then I'd recommend rolling back.

CC @song-jiang who is looking into a fix for this.

**Comment by song-jiang** [comment]
I am able to reproduce. kube-controller pod restarts successfully after crash.
