### ISSUE TITLE
When on earth the controllers in this repository are not needed?

### ISSUE THREAD

**Issue by calixwu** [projectcalico/kube-controllers#346]
The description here https://github.com/projectcalico/kube-controllers says: 

> This repository contains a collection of kubernetes controllers for Calico deployed using the etcd datastore. Note that when using Calico configured to use the Kubernetes datastore, the controllers in this repository are not needed.

I am confused. Why when using the etcd datastore, we have to run these controllers? What exactly these controllers do? I thought we run them only when using the k8s datastore... Is there any mistake about the description?

**Comment by caseydavenport** [comment]
The description is right for all currently released versions of Calico, though future versions may add functionality which runs one or more controllers in this repository when using Kubernetes API CRDs. 

This repository contains a number of different controllers which monitor the Kubernetes API and perform actions in response.

There's some more detail in the documentation here: https://docs.projectcalico.org/v3.5/reference/kube-controllers/configuration

**Comment by caseydavenport** [comment]
I will update the README, since Calico v3.6 will install this component for Kubernetes API as well (enablign the node controller).

**Comment by calixwu** [comment]
@caseydavenport Thanks. We never install any of these controllers before, but it seems to be running well.........  Thanks for the mistake correction.
