### ISSUE TITLE
calico-kube-controller container cannot be started without DNS options.

### ISSUE THREAD

**Issue by kernelt** [projectcalico/kube-controllers#357]
## Expected Behavior

calico-kube-controllers-xxxxxxxxx-xxxxx pod inside a kubernetes cluster **CAN** be running, when kubernetes node (worker) doesn't have valid DNS options at /etc/systemd/resolved.conf 

## Current Behavior

calico-kube-controllers-xxxxxxxxx-xxxxx pod inside a kubernetes cluster **CANNOT** be running, when kubernetes node (worker) doesn't have valid DNS options at /etc/systemd/resolved.conf. It leads to a non-opertional cluster and to many errors

> E0313 13:49:04.217426       1 reflector.go:205] github.com/projectcalico/kube-controllers/pkg/controllers/pod/pod_controller.go:208: Failed to list *v1.Pod: Get https://10.100.0.1:443/api/v1/pods?resourceVersion=0: dial tcp 10.100.0.1:443: getsockopt: connection refused

## Possible Solution

Remove the dns dependency, If possible.

## Steps to Reproduce (for bugs)

1. Remove all dns settings at /etc/systemd/resolved.conf from the kubernetes node (worker) which currently holds calico-kube-controllers-xxxxxxxxx-xxxxx pod
2. systemctl restart systemd-resolved
3. systemctl restart docker
4. systemctl restart kubelet
5. Re-run calico-kube-controllers-xxxxxxxxx-xxxxx pod on the same kubernetes node (worker) which doesn't have dns settings (from the first step).

## Context

Managing kubernetes cluster via kubespray doesn't work.

## Your Environment

* Kubernetes version (`kubectl version`): 
> Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}

> Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
* Manifest file used to deploy k8s policy:
>  kubespray (master branch) latest commit `commit/fd2c47b56a09c79a7068b2630014a8203fda7afb`, 13.03.19
* Operating System and version:
> Ubuntu 18.04.2 LTS \n \l
* Calico-kube-controllers image version: 
> quay.io/calico/kube-controllers:v3.4.0-amd64
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> Failed to list *v1.Pod: Get https://10.100.0.1:443/api/v1/pods?resourceVersion=0: dial tcp 10.100.0.1:443: getsockopt: connection refused

This particular error doesn't seem to be a DNS dependency - it already has resolved an address using some mechanism (10.100.0.1).

Is there some other interaction I'm missing?

The above error seems to indicate a problem with kube-proxy on that node.

**Comment by kernelt** [comment]
Maybe you are right and kube-proxy was fixed by restarting docker. Nevertheless, I can sum up that the kubernetes nodes (especially their network part with calico) are too sensitive to proper settings like dns, network (mtu), time sync etc. All of them must have an identical configuration. Thanks.
