### ISSUE TITLE
Most of policies changed on every reconciliation

### ISSUE THREAD

**Issue by jcmoraisjr** [projectcalico/kube-controllers#380]
Kube controllers log `Value for key has changed, ...` on every reconciliation (default, `5m`) for about 70% of network policy objects of my cluster.

## Expected Behavior

Kube controller should queue update only for changed policies.

## Current Behavior

Kube controller is queueing update for about 70% of network policies on every reconciliation.

## Possible Solution

Using debug level I can confirm that most of the changes are here:

* Cached: `NotNets:[]string{}`
* Updated: `NotNets:[]string(nil)`

## Steps to Reproduce (for bugs)

Run kube-controllers, create some k8s network policy objects, some of them should queue for update every 5 minutes on reconciliations.

## Your Environment
* Kubernetes version (`kubectl version`): `v1.13.4`
* Manifest file used to deploy k8s policy: running via k8s deployment, datastore is a dedicated etcd cluster
* Operating System and version: `CoreOS 2079.4.0`

**Comment by rikatz** [comment]
OK, so this is a though investigation. 

I've been taking a look into the Loop and it seems some objects are always in cache, while other are always in Datastore but a very little situation when they're in both.

Also, when they're in both, still we have a strange behavior of the DeepEqual if, where the objects don't seem really equal, although they are.

Some inspections here:

1) the condition '!existsInDatastore' or '!existsInCache' only happened to us when the type is converter.WorkloadEndpoint

2) I've put a log into here:
```
	// Build a map of existing keys in the datastore.
	allKeys := map[string]bool{}
	for key := range objMap {
		c.log.Warnf("---- Datastore Key: %v", key)
		allKeys[key] = true
	}

	// Also add all existing keys in the cache.
	for _, key := range c.ListKeys() {
		c.log.Warnf("---- Cache Key: %v", key)
		allKeys[key] = true
	}```

And the result is there when parsing this, it seems only a part of  the objects got caught by the Cache, while others are only in the Datastore.

An example:

```
$ cat log |egrep '(Cache Key|Datastore Key)' |grep NetworkPolicy |awk -F 'Key: ' '{ print $2 }' |sort |uniq -c

      2 sistemaa/knp.default.jboss type=v3.NetworkPolicy"
      1 sistemaa/knp.default.nginx type=v3.NetworkPolicy"
      1 zopeplone-d/knp.default.default-deny type=v3.NetworkPolicy"
      1 zopeplone-d/knp.default.egress-dbaas type=v3.NetworkPolicy"
      2 zopeplone-d/knp.default.egress-internet type=v3.NetworkPolicy"
      1 zopeplone/knp.default.egress-pods type=v3.NetworkPolicy"
      2 zopeplone-t/knp.default.egress-dbaas type=v3.NetworkPolicy"
      1 zopeplone-t/knp.default.egress-default type=v3.NetworkPolicy"
      2 zopeplone-t/knp.default.egress-pods type=v3.NetworkPolicy"
```
This happens with ingress and egress policies (this is only an extraction of the log)

I'm going to make a deeper debug into the comparision of the objects (DeepEqual) but it seems that it's really not putting together the cache and the datastore. Maybe there's some tuning or something missing here.

**Comment by fasaxc** [comment]
@rikatz Thanks for the sleuthing, this one is on our fix queue but no-one's had time to dig into it yet.  If you're thinking of putting up a patch, please reach out on the #calico-dev channel on our slack so we don't duplicate work.

**Comment by rikatz** [comment]
@fasaxc answered into slack but just to register here also. I've figured out that [this](https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/conversion/conversion.go#L622) is causing the difference between the policies in every DeepEqual call.

As this is into libcalico and not into kube-controllers I'm pretty afraid of submitting a patch and breaking other stuffs, so I need some adult supervision :)
