### ISSUE TITLE
panic during migration from flannel to calico

### ISSUE THREAD

**Issue by gylstorffq** [projectcalico/kube-controllers#435]
During the migration from  fannel to calico as described in https://docs.projectcalico.org/v3.10/getting-started/kubernetes/installation/migration-from-flannel a panic occurs.
## Expected Behavior

No Panic or message what went wrong
## Current Behavior

kubectl logs -n kube-system -l k8s-app=flannel-migration-controller shows a panic:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:58 +0x105
panic(0x14e7b00, 0x18dbde0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/projectcalico/kube-controllers/pkg/controllers/flannelmigration.daemonset.AddNodeSelector(0x14a3937, 0x15, 0xc00064e640, 0x16a5a0c, 0xb, 0xc000681f50, 0x0, 0x0)
        /go/src/pkg/controllers/flannelmigration/k8s_resources.go:173 +0x224
github.com/projectcalico/kube-controllers/pkg/controllers/flannelmigration.(*flannelMigrationController).Run(0xc000123ea0, 0x0, 0x14053b2, 0x2, 0xc000252180)
        /go/src/pkg/controllers/flannelmigration/migration_controller.go:193 +0x4f8
created by main.(*controllerControl).RunControllers
        /go/src/cmd/kube-controllers/main.go:365 +0x17e

## Steps to Reproduce (for bugs)

1. kubectl apply -f https://docs.projectcalico.org/v3.10/manifests/flannel-migration/calico.yaml
2. kubectl apply -f https://docs.projectcalico.org/v3.10/manifests/flannel-migration/migration-job.yaml

## Your Environment

* Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:21:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
* Manifest file used to deploy k8s policy:
* Operating System and version:
Debian 10

**Comment by tmjd** [comment]
This seems like maybe the same thing as https://github.com/projectcalico/calico/issues/2988
Could you try out the mitigation suggested there and report back the results?
Hope that helps.
