### ISSUE TITLE
Flannel-to-Calico migration controller ignores FLANNEL_NETWORK environment variable

### ISSUE THREAD

**Issue by seh** [projectcalico/kube-controllers#499]
## Expected Behavior

Per [the documentation for the Flannel-to-Calico migration controller](https://docs.projectcalico.org/getting-started/kubernetes/flannel/migration-from-flannel#modify-flannel-configuration), users are supposed to be able to set the "FLANNEL_NETWORK" environment variable on the "flannel-migration-controller" container in the pods created by [the "flannel-migration" _Job_](https://docs.projectcalico.org/manifests/flannel-migration/migration-job.yaml).

When setting this environment variable to a CIDR block that differs from the "FLANNEL_NETWORK" variable found in a _kube-flannel_ container's _/run/flannel/subnet.env_ file, the CIDR block from the environment variable should take precedence. The controller should create a default Calico _IPPool_ using the CIDR block specified in the environment variable.

## Current Behavior

The migration controller reads the "FLANNEL_NETWORK" environment and [logs its value](https://sourcegraph.com/github.com/projectcalico/kube-controllers@9814cc5/-/blob/cmd/kube-controllers/main.go#L131-L135), but later [it determines](https://sourcegraph.com/github.com/projectcalico/kube-controllers@9814cc5066924201f7d350c34316bd4d1d7fe070/-/blob/pkg/controllers/flannelmigration/migration_controller.go#L331-L337) that the "flannel-migration-config" _ConfigMap_'s "flannel_subnet_env" field is still empty, and proceeds to read the _/run/flannel/subnet.env_ file from a running pod. As part of r[eading that file](https://sourcegraph.com/github.com/projectcalico/kube-controllers@9814cc5066924201f7d350c34316bd4d1d7fe070/-/blob/pkg/controllers/flannelmigration/migration_controller.go#L267-L275), transcribing its findings into a `flannelmigration.Config` struct, [it unconditionally **replaces** a previous value in the `flannelmigration.Config.FlannelNetwork` field](https://sourcegraph.com/github.com/projectcalico/kube-controllers@9814cc5066924201f7d350c34316bd4d1d7fe070/-/blob/pkg/controllers/flannelmigration/migration_controller.go#L267-L275) with the value read from the _/run/flannel/subnet.env_ file.

The migration controller thus [creates the the "default-ipv4-ippool" Calico _IPPool_](https://sourcegraph.com/github.com/projectcalico/kube-controllers@9814cc5066924201f7d350c34316bd4d1d7fe070/-/blob/pkg/controllers/flannelmigration/ipam_migrator.go#L92-L93) using the wrong CIDR block: it uses the one from the _/run/flannel/subnet.env_ file instead of the different one from the environment variable.

## Possible Solution

Before overwriting a previous value stored in the `flannelmigration.Config.FlannelNetwork` field, preserve an existing value there and only store a replacement value if the original value was empty (or maybe invalid).

## Steps to Reproduce (for bugs)
1. Create a Kubernetes cluster using _kops_ with Canal as the CNI.
1. Modify the pre-migration Calico manifest set to specify the "CALICO_IPV4POOL_CIDR" environment variable on the "calico-node" containers in the "calico-node" _DaemonSet_.
1. Apply those manifests.
1. Modify the migration _Job_ manifest set to specify the "FLANNEL_NETWORK" environment variable on the "flannel-migration-controller" container in the "flannel-migration" _Job_.
1. Apply those manifests.
1. Follow the logs from the migration controller.  
  _kubectl --namespace=kube-system logs job/flannel-migration --follow_
1. Notice that it logs the value from the "FLANNEL_NETWORK" environment variable first, then later logs the value found in the _/run/flannel/subnet.env_ file, having stored that in the "flannel-migration-config" _ConfigMap_.
1. After the migration controller is underway, inspect the "default-ipv4-ippool" Calico _IPPool_, and observe that its "spec.cidr" field has the wrong value.

## Context

I'm unable to migrate a _kops_-provisioned cluster that starts with Flannel using a CIDR block of _100.64.0.0/10_ to having Calico use a default _IPPool_ with a CIDR block of _100.96.0.0/11_, as _kops_ prefers for Calico. If the migration controller creates an _IPPool_ using _100.64.0.0/10_, I can't even create a sibling _IPPool_ using _100.96.0.0/11_, because the former subsumes the latter. Disabling the former first isn't enough to disable that validation.

See [this epic thread in the "install" channel](https://calicousers.slack.com/archives/CPTH1KS00/p1598358426020400) of the Calico Slack team for more context.

## Your Environment
* Kubernetes version (`kubectl version`):  
  `version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
* Manifest file used to deploy k8s policy:  
  _Not applicable_
* Environment:  
  AWS EC2 (atop _m5.large_ and _m5.xlarge_ instance types)
* Operating System and version:  
  Client side: macOS 10.15.6
  Server side: Flatcar Container Linux "beta" channel (2513.2)
  (_uname -a_ reports `Linux ip-10-3-5-174.us-east-2.compute.internal 5.4.59-flatcar #1 SMP Wed Aug 19 12:45:05 -00 2020 x86_64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz GenuineIntel GNU/Linux`)

**Comment by seh** [comment]
Here is how I worked around this problem for now.

I fetched the existing content of the _/run/flannel/subnet.env_ file and adapted it to the format demanded for the _ConfigMap_ field:
```shell
% kubectl --namespace=kube-system exec -it canal-n4tgt -c kube-flannel -- \
    cat /run/flannel/subnet.env \
    | tr -d '\r' \
    | paste -s -d ';' - \
    | sed 's!100\.64\.0\.0/10!100.96.0.0/11!'
FLANNEL_NETWORK=100.96.0.0/11;FLANNEL_SUBNET=100.96.1.1/24;FLANNEL_MTU=8951;FLANNEL_IPMASQ=true
```
I then specified that value in the "flannel-migration-config" _ConfigMap_, amending the definition from [the migration _Job_ manifest set](https://docs.projectcalico.org/manifests/flannel-migration/migration-job):
```yaml
# This ConfigMap is used to store Flannel subnet.env content.
kind: ConfigMap
apiVersion: v1
metadata:
  name: flannel-migration-config
  namespace: kube-system
data:
  # [seh]: Here we replace the value for the "FLANNEL_NETWORK" value
  # that it would have found, which is 100.64.0.0/10.
  flannel_subnet_env: "FLANNEL_NETWORK=100.96.0.0/11;FLANNEL_SUBNET=100.96.6.1/24;FLANNEL_MTU=8951;FLANNEL_IPMASQ=true"
```
That tricks the migration controller into not reading the _/run/flannel/subnet.env_ file from any pods to determine the "FLANNEL_NETWORK" value.

**Comment by song-jiang** [comment]
Thanks @seh for the details and the workaround. Env variables `FLANNEL_NETWORK FLANNEL_SUBNET FLANNEL_MTU FLANNEL_IPMASQ` has to be set as one item via `flannel_subnet_env` from the configMap. Your workaround is actually the right customisation procedure. I believe we should fix Calico doc to make it clearer.

**Comment by seh** [comment]
Are you saying that you never intended to read these from the environment in the migration controller? Using `envconfig.Process` to initialize the configuration seems like it _was_ going out of its way trying to use the separate environment variables.

If instead you now prescribe changing the _ConfigMap_, I think you should respect separate fields in the _ConfigMap_ for each of these four values. It's a weird and brittle detail to ask users to engage: "Take your four field values join them wit the field names, separating the pairs with semicolons, then set that string as the value of this one field."

Can you see how that's a lot of accidental complexity dumped at the users' feet?

**Comment by song-jiang** [comment]
@seh I understand it is a bit complicated for user to pass ENV variables. However, these variables are normally meant to be auto-detected. It is risky for user to modify those values. In your context, if you use a smaller CIDR range for Calico than the original one, there is a chance IPAM migration may fail for nodes use CIDR range outside a Calico ippool.

**Comment by seh** [comment]
> It is risky for user to modify those values.

GIven that, I think we should remove the migration controller's current reading of those environment variables, and adjust the documentation to match.

> In your context, if you use a smaller CIDR range for Calico than the original one, there is a chance IPAM migration may fail for nodes use CIDR range outside a Calico ippool.

Yes, [I've asked about this several times](https://calicousers.slack.com/archives/CPTH1KS00/p1598371917030100?thread_ts=1598358426.020400&cid=CPTH1KS00) in the "install" channel of the "Calico Users" Slack team (again [here](https://calicousers.slack.com/archives/CPTH1KS00/p1598375066032000?thread_ts=1598358426.020400&cid=CPTH1KS00) and [here](https://calicousers.slack.com/archives/CPTH1KS00/p1598452780038400?thread_ts=1598358426.020400&cid=CPTH1KS00)). So far I haven't seen it fail, but given that you're concerned that it _can_ fail, how do you recommend your users migrate from a pool with a wider CIDR block to a narrower one? At present, it's not possible to create a second pool, even with the original pool disabled.

**Comment by song-jiang** [comment]
> GIven that, I think we should remove the migration controller's current reading of those environment variables, and adjust the documentation to match.
Agree. We need to make the doc clearer on this.

> how do you recommend your users migrate from a pool with a wider CIDR block to a narrower one
I am afraid migration controller is not designed to convert CIDR blocks because nodes running on a previous wider CIDR block could have subnet allocated outside of the narrower one, they will be cut off from the network (no vxlan routes) during migration process. However, migrate from a narrower CIDR block to a wider one is possible.

**Comment by seh** [comment]
> I am afraid migration controller is not designed to convert CIDR blocks because nodes running on a previous wider CIDR block could have subnet allocated outside of the narrower one, they will be cut off from the network (no vxlan routes) during migration process. However, migrate from a narrower CIDR block to a wider one is possible.

Thank you for the clarification and the warning. In my case, I think I'm going to have to take that risk. We'll be evicting all the pods shortly after migration as we replace the worker machines hosting them, so if we spot any pods that appear to have lost their network connection right after migration, we can delete those right then and let their supervising controller replace them.

As I mentioned in Slack, I suspect that in _kops_ we wind up with Flannel and Calico configured in incompatible ways. The Flannel network CIDR block is the wider one, and subsumes the Kubernetes _Service_ CIDR block. The Calico default _IPPool_ is narrower, and sits as a sibling to the Kubernetes _Service_ CIDR block. I think—but would appreciate your confirmation—that it's bad for a Calico _IPPool_ to overlap with the Kubernetes _Service_ CIDR block, as the Kubernetes API server is supposed to own IPAM in that block. [The documentation](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/#options) for the `--service-cluster-ip-range` command-line flag accepted by the API server reads as follows:
> A CIDR notation IP range from which to assign service cluster IPs. This must not overlap with any IP ranges assigned to nodes or pods.

If I allow Calico's default _IPPool_ to assume the same CIDR block as Flannel had been using for its network, we could have pod IP addresses colliding with _Service_ cluster IP addresses.

**Comment by song-jiang** [comment]
@seh Thanks for detailed analysis on `kops` and issues we may have. 
> Flannel network CIDR block is the wider one, and subsumes the Kubernetes Service CIDR block
I am not familiar with kops, but won't that to be the same problem for Service CIDR overlapping pod CIDR with Flannel?

**Comment by seh** [comment]
> won't that to be the same problem for Service CIDR overlapping pod CIDR with Flannel?

I _think_ so. I don't know why this isn't causing a problem for anyone yet. Perhaps I'm misinterpreting what Flannel does with that CIDR block.

**Comment by caseydavenport** [comment]
So, if I understand correctly, the migration procedure is not intended to support changing the pod CIDR during the migration. 

I think what I'd recommend is to do the migration, keeping the same CIDR, and then follow the steps to change Calico's IP pool after the migration completes. 

I understand this adds an extra step, but the capabilities do currently exist to do what you need,  I think.

**Comment by seh** [comment]
> I think what I'd recommend is to do the migration, keeping the same CIDR, and then follow the steps to change Calico's IP pool after the migration completes.

What is the procedure for changing an _IPPool_ like that?

_(This was a blast from the past, even though I'm still dealing with it for a couple more migrations.)_

**Comment by caseydavenport** [comment]
This is the documented procedure for it: https://docs.projectcalico.org/archive/v3.18/networking/migrate-pools

Let me know if that sort of thing covers what's needed here! I'm sorta only partially up-to-speed on this issue.

**Comment by seh** [comment]
I think we've exhausted the topic. It's still not clear how Flannel was working properly before in _kOps_, and the migration controller is not poised to correct that problem.

For my own needs, we're now past these concerns, having upgraded all of our clusters that had been using Flannel. I still think there are corrections that would help users of the migration controller, avoiding confusion as to whether they should be able to control it with environment variables or by editing its _ConfigMap_. That's all stated above.

If you'd like to close the issue now, I understand.
