### ISSUE TITLE
crash on named port

### ISSUE THREAD

**Issue by cjyar** [projectcalico/kube-controllers#93]
Kubernetes Services and Ingresses allow one to reference ports by name or number. If I create a NetworkPolicy that references a port by name, the calico-policy-controller crashes.

```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: bad-np
spec:
  ingress:
  - ports:
    - port: my-port
      protocol: TCP
  podSelector:
    matchLabels:
      app: my-app
```

Here's the output from the policy controller:

```
2017-04-28 15:34:36,814 7 ERROR Error parsing policy: {
  "spec": {
    "ingress": [
      {
        "ports": [
          {
            "protocol": "TCP",
            "port": "my-port"
          }
        ]
      }
    ],
    "podSelector": {
      "matchLabels": {
        "app": "my-app"
      }
    }
  },
  "metadata": {
    "name": "bad-np",
    "generation": 1,
    "namespace": "my-namespace",
    "resourceVersion": "4165855",
    "creationTimestamp": "2017-04-07T20:39:17Z",
    "selfLink": "/apis/extensions/v1beta1/namespaces/my-namespace/networkpolicies/bad-np",
    "uid": "4543f3a6-1bd2-11e7-9402-005056b28820"
  }
}
Traceback (most recent call last):
  File "handlers/network_policy.py", line 28, in add_update_network_policy
  File "policy_parser.py", line 68, in calculate_inbound_rules
  File "policy_parser.py", line 149, in _allow_incoming_to_rules
  File "site-packages/pycalico/datastore_datatypes.py", line 441, in __init__
  File "site-packages/pycalico/datastore_datatypes.py", line 458, in __setitem__
ValueError: '[u'my-port']' is not allowed for key 'dst_ports'
Traceback (most recent call last):
  File "<string>", line 516, in <module>
  File "<string>", line 165, in run
  File "<string>", line 257, in read_updates
  File "<string>", line 288, in _process_update
  File "handlers/network_policy.py", line 34, in add_update_network_policy
AttributeError: 'module' object has no attribute 'exit'
controller returned -1
```

The policy controller exits, and Kubernetes restarts it. Other NetworkPolicies may or may not get processed, depending on what order the policy controller gets to them.

Some possible fixes:

* Allow Calico to read named ports. The [docs](https://kubernetes.io/docs/api-reference/v1.6/#networkpolicyport-v1beta1-extensions) say it's legal syntax.
* Fail to parse, but don't crash.
* Add an event to the NetworkPolicy or the Pod explaining the error. Otherwise a non-admin user won't be able to tell what's going wrong or what caused it.

**Comment by caseydavenport** [comment]
@cjyar thanks for raising.

As you've discovered, Calico doesn't yet support named ports (no implementations currently support that feature).

I think we should at _least_ fail to parse but not crash.  An event to indicate that the policy is not being enforced would be even better.

Adding this feature requires additional Felix support, and is probably a ways down the road yet.

**Comment by fasaxc** [comment]
Work in progress under https://github.com/projectcalico/felix/pull/1534

**Comment by fasaxc** [comment]
@bcreane Since named ports has been pushed out to >v2.6, do we need to do anything here to validate?

**Comment by caseydavenport** [comment]
We should at least have a UT which converts a policy with a named port and validates it doesn't panic.

**Comment by bcreane** [comment]
Named port functionality is supported in `v3.0.0-alpha1`. There's a named port e2e which validates correct behavior:  https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/network_policy.go#L281

In addition, there's good UT coverage for rules w/named ports: https://github.com/projectcalico/libcalico-go/pull/515/commits/dc54dc76b5be98cc7142b0b1c1a769608ec7af4c

@cjyar - if you get a chance to check this against v3.0.0-alpha1 or newer builds, I'd greatly appreciate hearing from you. I'll leave the issue open a bit longer.

**Comment by cjyar** [comment]
@bcreane I'll try to test that this week.

**Comment by caseydavenport** [comment]
This is no longer manifesting in master + v3.0-alpha/beta releases.
